name: build .Net and Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    # .net ci/cd

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'
        dotnet-quality: 'ga'

    - name: Restore .NET dependencies
      working-directory: ./CSharp
      run: dotnet restore aoc2025.csproj

    - name: Build .NET
      working-directory: ./CSharp
      run: dotnet build aoc2025.csproj --no-restore --configuration Release

    - name: Test .NET
      working-directory: ./CSharp
      run: dotnet test aoc2025.csproj --no-build --verbosity normal --configuration Release

